export const plans = {
  monthly: [
    {
      id: "free",
      title: "Miễn phí",
      price: "0đ",
      period: "/tháng",
      description: "Bắt đầu nấu ăn với Nutrimate",
      features: [
        { text: "10 công thức mỗi tháng", included: true },
        { text: "Tìm kiếm công thức cơ bản", included: true },
        { text: "Lưu 5 công thức yêu thích", included: true },
        { text: "Kế hoạch bữa ăn hàng tuần", included: false },
        { text: "Danh sách mua sắm tự động", included: false },
        { text: "Tùy chỉnh công thức", included: false },
        { text: "Không quảng cáo", included: false },
      ],
      button: "Bắt đầu miễn phí",
      variant: "outline",
    },
    {
      id: "basic",
      title: "Cơ bản",
      badge: "Phổ biến nhất",
      price: "99.000đ",
      period: "/tháng",
      description: "Dành cho những người yêu thích nấu ăn",
      features: [
        { text: "Không giới hạn công thức", included: true },
        { text: "Tìm kiếm công thức nâng cao", included: true },
        { text: "Lưu không giới hạn công thức", included: true },
        { text: "Kế hoạch bữa ăn hàng tuần", included: true },
        { text: "Danh sách mua sắm tự động", included: true },
        { text: "Tùy chỉnh công thức", included: false },
        { text: "Không quảng cáo", included: false },
      ],
      button: "Đăng ký ngay",
      variant: "default",
    },
    {
      id: "premium-monthly",
      title: "Cao cấp (Tháng)",
      price: "199.000đ",
      period: "/tháng",
      description: "Trải nghiệm đầy đủ tính năng của Nutrimate",
      features: [
        { text: "Tất cả tính năng của gói Cơ bản", included: true },
        { text: "Tùy chỉnh công thức theo sở thích", included: true },
        { text: "Không quảng cáo", included: true },
        { text: "Tạo công thức từ ảnh nguyên liệu", included: true },
        { text: "Phân tích dinh dưỡng chi tiết", included: true },
        { text: "Hỗ trợ ưu tiên 24/7", included: true },
        { text: "Chia sẻ kế hoạch với gia đình", included: true },
      ],
      button: "Đăng ký ngay",
      variant: "default",
    },
  ],
  yearly: [
    {
      id: "premium-weekly",
      title: "Cao cấp (Tuần)",
      price: "59.000đ",
      period: "/tuần",
      description: "Tận hưởng trải nghiệm ngắn hạn với tất cả tính năng",
      features: [
        { text: "Tất cả tính năng của gói Cơ bản", included: true },
        { text: "Tùy chỉnh công thức theo sở thích", included: true },
        { text: "Không quảng cáo", included: true },
        { text: "Tạo công thức từ ảnh nguyên liệu", included: true },
        { text: "Phân tích dinh dưỡng chi tiết", included: true },
        { text: "Hỗ trợ ưu tiên 24/7", included: true },
        { text: "Chia sẻ kế hoạch với gia đình", included: true },
      ],
      button: "Đăng ký ngay",
      variant: "default",
    },
    {
      id: "premium-yearly",
      title: "Cao cấp (Năm)",
      price: "1.899.000đ",
      period: "/năm",
      description: "Giá trị cao nhất – tiết kiệm đến 400.000đ",
      features: [
        { text: "Tất cả tính năng của gói Cơ bản", included: true },
        { text: "Tùy chỉnh công thức theo sở thích", included: true },
        { text: "Không quảng cáo", included: true },
        { text: "Tạo công thức từ ảnh nguyên liệu", included: true },
        { text: "Phân tích dinh dưỡng chi tiết", included: true },
        { text: "Hỗ trợ ưu tiên 24/7", included: true },
        { text: "Chia sẻ kế hoạch với gia đình", included: true },
      ],
      button: "Đăng ký ngay",
      variant: "default",
    },
  ],
};