export const recipeSeeds = [
    {
        name: "Bữa sáng yến mạch táo",
        description: "Yến mạch táo quế giàu chất xơ và dễ nấu.",
        image: "/images/oat-apple.jpg",
        prepTime: "5 phút",
        cookTime: "10 phút",
        totalTime: "15 phút",
        servings: 1,
        calories: 320,
        difficulty: "Dễ",
        tags: ["bữa sáng", "healthy"],
        ingredients: [
            { name: "Yến mạch", amount: "50g" },
            { name: "Táo", amount: "1 quả" },
            { name: "Quế", amount: "1/2 thìa cà phê" },
        ],
        steps: [
            { title: "Chuẩn bị", description: "Rửa và cắt nhỏ táo." },
            { title: "Nấu", description: "Nấu yến mạch với nước, thêm táo và quế." },
        ],
        nutrition: { calories: 320, protein: 8, carbs: 55, fat: 6, fiber: 7, sugar: 15 },
        tips: ["Có thể thêm sữa hạnh nhân để béo ngậy hơn"],
        relatedRecipes: [],
        videoUrl: "https://youtube.com/watch?v=example1",
    },
    {
        name: "Ức gà áp chảo",
        description: "Ức gà áp chảo nhanh gọn với rau củ.",
        image: "/images/grilled-chicken.jpg",
        prepTime: "10 phút",
        cookTime: "20 phút",
        totalTime: "30 phút",
        servings: 2,
        calories: 450,
        difficulty: "Trung bình",
        tags: ["bữa trưa", "giàu đạm"],
        ingredients: [
            { name: "Ức gà", amount: "200g" },
            { name: "Bông cải xanh", amount: "100g" },
            { name: "Tỏi băm", amount: "1 thìa" },
        ],
        steps: [
            { title: "Ướp", description: "Ướp gà với muối, tiêu, tỏi." },
            { title: "Áp chảo", description: "Áp chảo gà đến khi chín vàng." },
        ],
        nutrition: { calories: 450, protein: 40, carbs: 20, fat: 20, fiber: 5, sugar: 4 },
        tips: ["Thêm dầu ô liu để gà mềm hơn"],
        relatedRecipes: [],
        videoUrl: "https://youtube.com/watch?v=example2",
    },
    {
        name: "Salad cá ngừ",
        description: "Salad cá ngừ thanh mát, giàu protein.",
        image: "/images/tuna-salad.jpg",
        prepTime: "10 phút",
        cookTime: "0 phút",
        totalTime: "10 phút",
        servings: 2,
        calories: 250,
        difficulty: "Dễ",
        tags: ["bữa tối", "healthy", "salad"],
        ingredients: [
            { name: "Cá ngừ hộp", amount: "1 hộp (150g)" },
            { name: "Xà lách", amount: "100g" },
            { name: "Cà chua bi", amount: "50g" },
        ],
        steps: [
            { title: "Chuẩn bị", description: "Rửa rau và cắt nhỏ." },
            { title: "Trộn", description: "Trộn cá ngừ, rau, cà chua với nước sốt." },
        ],
        nutrition: { calories: 250, protein: 30, carbs: 10, fat: 10, fiber: 4, sugar: 3 },
        tips: ["Dùng sốt dầu giấm thay vì mayonnaise để ít calo hơn"],
        relatedRecipes: [],
        videoUrl: "https://youtube.com/watch?v=example3",
    },
    {
        name: "Sinh tố chuối bơ đậu phộng",
        description: "Đồ uống giàu năng lượng, thích hợp sau khi tập luyện.",
        image: "/images/banana-pb-smoothie.jpg",
        prepTime: "5 phút",
        cookTime: "0 phút",
        totalTime: "5 phút",
        servings: 1,
        calories: 380,
        difficulty: "Dễ",
        tags: ["sinh tố", "sau tập"],
        ingredients: [
            { name: "Chuối", amount: "1 quả" },
            { name: "Bơ đậu phộng", amount: "2 thìa" },
            { name: "Sữa hạnh nhân", amount: "200ml" },
        ],
        steps: [
            { title: "Xay", description: "Cho tất cả nguyên liệu vào máy xay, xay nhuyễn." },
        ],
        nutrition: { calories: 380, protein: 12, carbs: 50, fat: 15, fiber: 6, sugar: 20 },
        tips: ["Thêm đá để mát lạnh hơn"],
        relatedRecipes: [],
        videoUrl: "https://youtube.com/watch?v=example4",
    },
    {
        name: "Phở bò",
        description: "Món truyền thống Việt Nam với nước dùng đậm đà.",
        image: "/images/pho-bo.jpg",
        prepTime: "30 phút",
        cookTime: "2 giờ",
        totalTime: "2 giờ 30 phút",
        servings: 4,
        calories: 600,
        difficulty: "Khó",
        tags: ["món truyền thống", "phở"],
        ingredients: [
            { name: "Xương bò", amount: "1kg" },
            { name: "Thịt bò tái", amount: "300g" },
            { name: "Bánh phở", amount: "400g" },
            { name: "Hành, gừng, gia vị phở", amount: "vừa đủ" },
        ],
        steps: [
            { title: "Ninh xương", description: "Ninh xương bò ít nhất 2 giờ." },
            { title: "Trụng bánh phở", description: "Trụng bánh phở trong nước sôi." },
            { title: "Hoàn thành", description: "Cho thịt bò, hành, rau thơm và chan nước dùng." },
        ],
        nutrition: { calories: 600, protein: 35, carbs: 65, fat: 20, fiber: 3, sugar: 2 },
        tips: ["Thêm quế, hồi để nước dùng thơm hơn"],
        relatedRecipes: [],
        videoUrl: "https://youtube.com/watch?v=example5",
    },
]
